### ISSUE TITLE
大佬 博客的python源码应该如何执行阿 

### ISSUE THREAD

**Issue by huanx9** [lxmymjr/lxmymjr.github.io#1]
是否有依赖 为什么运行总是报错。。

**Comment by lxmymjr** [comment]
哪个

**Comment by huanx9** [comment]
https://lxmymjr.github.io/contents/%E4%B8%BB%E6%B5%81%E8%A7%86%E9%A2%91%E7%BD%91%E7%AB%99%E5%BC%B9%E5%B9%95%E4%B8%8B%E8%BD%BD

这篇文章，我把源码修改成 *.py 执行报错。 然后我想把url 替换掉 依然执行不了。
有空的话，讲讲方法呗。

**Comment by lxmymjr** [comment]
你要说仔细一点，我这里面有好几个代码，哪个报错，报错是报什么错。

**Comment by huanx9** [comment]
每个源码里面都需要自己替换变量吗？
反正每一个都跑不起来啦。 不知道怎么玩 = =

**Comment by huanx9** [comment]
不如直接开个仓库，直接开源出来咋样~~~
